### ISSUE TITLE
Torches cannot be seen by Hwyla

### ISSUE THREAD

**Issue by WenXin20** [EndlesNights/TorchSlab#1]
Forge v28.1.111
Torch Slabs v1.2
Hwyla v1.10.6-B67

When looking at the Torch Slab, Hwyla doesn't display any information.

Check this issue for plugin info: TehNut/HWYLA#68

**Comment by EndlesNights** [comment]
I might have just fixed this in the latest version up of v1.3. If the problem still persist message me back and I'll take a closer look.

**Comment by WenXin20** [comment]
Alright, I'll check it out

**Comment by WenXin20** [comment]
Yep, it worked, thanks!
