### ISSUE TITLE
a spelling mistake in config file

### ISSUE THREAD

**Issue by ghost** [EndlesNights/TorchSlab#10]
TorchSlab 1.15.2 v1.6.6

just noticed a small spelling error in the torchslabmod-server.toml file

You spelled `minecraft:barel` instead of `minecraft:barrel` in the interactiveCheckList section

**Comment by EndlesNights** [comment]
Woops small mistake that I'll be sure to fix and push out. But you can always just fix it in your config file for the time being on your own end.

Thanks for the feed back & have a nice day.
