### ISSUE TITLE
Server / Log & Errors

### ISSUE THREAD

**Issue by TheSnowyChickens** [EndlesNights/TorchSlab#11]
Hello,
I just started my modpack with your mod on a server and I found a heavy error spam in the console.

[2020-04-21-1.log](https://github.com/EndlesNights/TorchSlab/files/4507492/2020-04-21-1.log)
(I can't load it up to Pastebin.net, because the file it to big/heavy)

These errors just scare me to use the mod on a server, I don't think that they destroy something. :D

Is that something, that you can fix ?

MC: 1.15.2
Forge: 31.1.47
TorchSlabs: v1.6.8

**Comment by EndlesNights** [comment]
Oh, so those are the loot tables that work in conjunctions with the compatibility (most of which are Buzzies Bees Modr ) So it's just throwing up an error when attempting to load those loot tables, but is unable to find the block to attach it to. 
Shouldn't cause you any trouble during run time, but a quick fix you can do is to open the mods jar file up with an archive. 
Navigate to "torchslabmod-1.15.2_v1.6.8.jar\data\torchslabmod\loot_tables\blocks"
Delete all the .json files inside of that folder with the exception of "end_rod_slab.json", "pad_torch.json" and "pad_lantern.json"

**Comment by TheSnowyChickens** [comment]
Okay, good to know.

Ty :)

Edit: ahh, a more empty console <3
