### ISSUE TITLE
Support for end rods

### ISSUE THREAD

**Issue by tyra314** [EndlesNights/TorchSlab#2]
It would be nice, if you could add support for end rods, so one can place them on top and bellow slaps as well.

![2020-02-01_01 56 18](https://user-images.githubusercontent.com/16997177/73584060-254fee80-4496-11ea-80fb-02d97d76405d.png)

**Comment by EndlesNights** [comment]
Sure thing, will look into implementing this over the weekend some time.

**Comment by tyra314** [comment]
I just realized that this isn't as simple as I originally thought, because you can stack end rods on top of each other. So you probably need to "move" the whole stack...

**Comment by EndlesNights** [comment]
![2020-02-08_21 00 53](https://user-images.githubusercontent.com/58280840/74095104-ee8f5f00-4ab9-11ea-8508-2d1274220583.png)

Just want to clean this up a bit but the spaghetti code is in place.

**Comment by EndlesNights** [comment]
End rod support has been added into the latest version.
