### ISSUE TITLE
v1.6.10  crashes client

### ISSUE THREAD

**Issue by ClaudiusMinimus** [EndlesNights/TorchSlab#20]
I'm using your Torch Slab Mod in my 1.15.2 mod pack. When I updated from v1.6.8 to v1.6.10 my client crashes.
- OS: Linux Mint 19.3
- Minecraft: 1.15.2
- Torch Slab Mod mc 1.15.2 v1.6.10
https://paste.ee/p/lJDfg

Also: When I revert to v1.6.8 and updated FancyMenuWhen my client crashes and it looks like Torch Slab Mod is the culprit:

https://paste.ee/p/jz6d2

**Comment by BedrockLegends** [comment]
@ClaudiusMinimus Fancymenu is working on updating to the most released version of forge, I contacted the developer this morning

**Comment by EndlesNights** [comment]
Does the 1.6.13 patch fix your crash issue?

**Comment by ClaudiusMinimus** [comment]
Sorry, it does not, though if I just load your mod and the latest of fancymenu it loads fine. There must be another conflict.
