### ISSUE TITLE
Loot Table Parsing Errors

### ISSUE THREAD

**Issue by kornfan6589** [EndlesNights/TorchSlab#22]
Quite a few parsing errors on server startup. Could just be console spam but thought it was worth noting. 

Clipped list of the errors here: https://pastebin.com/XNj9Rc1V

Running Forge 31.1.87
Torch Slab mod 1.6.13
MC 1.15.2

Mod List: https://pastebin.com/BC7c0sKb

**Comment by EndlesNights** [comment]
Just console spam if you don't have the relevant mods, no easy way for me to disable it sorry. You can go into the jar, navigate to data/torchslabmod/loot_talbes/blocks and manually remove the .json files you do not wish to use if it bothers you. (In you're case the quark based ones)
Sorry about that.

**Comment by kornfan6589** [comment]
All good, just wanted to confirm it was spam. Working on cleaning up errors in our modpack. Thanks for the speedy reply!
