### ISSUE TITLE
1.16.1 Log spammed with errors regarding blocks not found

### ISSUE THREAD

**Issue by HatTrkPatrk** [EndlesNights/TorchSlab#25]
With forge 1.16.1 ...-106 the console log is littered with "Can't find block" errors

Another user in the CurseForge comments for the mod posted his log https://www.curseforge.com/minecraft/mc-mods/torchslabs-mod?comment=115

Mine is the same general error. He cut his log off at the 2nd error so I'll just put here that doing a search count for "Can't find block torchslabmod" found 106 such errors in the server startup.

Running forge 1.16.1 ...-106 with "Torch Slab Mod mc 1.16.1 v1.6.16" downloaded from CurseForge.

**Comment by Kai-Kramer** [comment]
I second this one, it's also an issue on MC 1.15.2: `torchslabmod-1.15.2_v1.7.0`

I tried to paste all of the logged errors into pastebin, but was met with a 512kb upload limit. Split it up into 3 separate pastes, totalling ~11,000 lines. Any client that is running your mod is met with like, a megabyte of logged errors every time a world is loaded.

Logs:
[First](https://pastebin.com/8gDp0z60)
[Second](https://pastebin.com/fGtFC0Xp)
[Third](https://pastebin.com/cRY4rkg2)

Modlist: https://pastebin.com/i4axD4nr

**Comment by djmattyg007** [comment]
Confirming I experience the same issue, also in 1.15.2. It makes diagnosing real issues absurdly difficult.

**Comment by TheNathanSpace** [comment]
Yeah, this is sort of ridiculous. I assume it hasn't been fixed?

**Comment by MarioSMB** [comment]
1.16.5 user here, still getting heavy log spam on my server during launch:  
[torchslab_spam.txt](https://github.com/EndlesNights/TorchSlab/files/6228864/torchslab_spam.txt)

Any solutions would be appreciated, as this makes up 85% of the startup log.

**Comment by MarioSMB** [comment]
Part of this is due to Buzzier Bees having changed their mod ID from "buzzierbees" to "buzzier_bees".

**Comment by MarioSMB** [comment]
I really hope the original developer returns and solves this, in the meantime I've made a datapack which resolves the spam: EDIT: Pack deleted, this has been fixed upstream!
Nullifying those loot tables as I have done should be perfectly safe, as it's hardcoded to not enable those blocks when the incorrect "buzzierbees" mod is checked... The only one I couldn't test is the bamboo blocks ones as I don't use that mod.

**Comment by Matthysse** [comment]
Thanks for making this fix it's awesome it really works!

**Comment by MarioSMB** [comment]
This appears to have been fixed in the latest version of the mod, and can be safely closed.
