### ISSUE TITLE
[1.15.2] Torches think every solid block is a slab.

### ISSUE THREAD

**Issue by Gbergz** [EndlesNights/TorchSlab#3]
Title^

Picture:
![2020-02-06_13 52 40](https://user-images.githubusercontent.com/26634554/73938722-22b32600-48e8-11ea-98a8-fd0e53a2d249.png)

Is this intended? It does not feel like it.
It also replaces the normal place sound with something else.

**Forge**: 31.1.0
**Minecraft**: 1.15.2
**Mod-Version**: 2.1.1-rc0

**Comment by EndlesNights** [comment]
This is an intended feature. 
Similar to how you place half slabs, you should aim for the top half of the block you watch the wall torch to appear on the top half of the block. If you want the wall torch to appear on the bottom half as it is normally, aim for the bottom half of the block. 
If you do not enjoy this feature and prefer only normal wall placement than I will add in a configurable option in the next update to turn this specific element off. Though I am curious as to what part of it makes it feel unintended?

As for the sound, it should be inherited directly from the torch sound effects. I will further investigate.
