### ISSUE TITLE
Torches/Lanterns on Lilypads + Mod support

### ISSUE THREAD

**Issue by Matthysse** [EndlesNights/TorchSlab#5]
Hello!
I think it would be cool to be able to place lanterns or torches on top of Lily pads for outdoor decoration !

+ it would be nice to support other mods like Buzzier bees which adds new candles. Why not add a mod compatibility to be able to place those candles on slabs.

**Comment by EndlesNights** [comment]
Love it. Currently preoccupied but I will write and push this out some time this week.

**Comment by Matthysse** [comment]
Thanks for considering my suggestion ! I love your mod !

**Comment by EndlesNights** [comment]
![2020-03-14_18 54 18](https://user-images.githubusercontent.com/58280840/76693013-0e73ee80-6635-11ea-9d29-92dcce67d3ca.png)

Base foundation is set up, just working out some interaction nuances and then grind out of all the variants.

**Comment by Matthysse** [comment]
It's just perfect, better than I imagined! Those candles on lily pads will add more atmosphere to zen gardens.

**Comment by EndlesNights** [comment]
Update has been added to curseforge. I'd love to see an image of your zen garden some time.

**Comment by Matthysse** [comment]
I can't see the update yet. Yes I can show you my garden but I wait for Optifine 1.15.2 compatible with forge because 1.15.2 on singleplayer is REAAALLY laggy.
Thanks for adding my suggestion, finally a modder who listens to feature requests :D !
