### ISSUE TITLE
[Suggestion] Yes.. another :)

### ISSUE THREAD

**Issue by Matthysse** [EndlesNights/TorchSlab#6]
Hello, yes it's me ... again !

When I saw your mod I immediatly had an idea. I saw many mods which adds that but they never lived long. I'm speaking about snow on slabs, stairs, walls and fences. There was mods which added that but they were very old but well-done (look at this seriously, it's epic ! : https://www.youtube.com/watch?v=qTe36G85GO4) and now they are badly-done : I don't know why but the new mods add the top snowy-grass texture on blocks with snow on top of it, but those blocks aren't grass !!! This is the case with the Snow Real Magic mod which creates a new block for every single variant of the model (stairs, slabs) for snow, so when we remove the mod in an area where it snowed, all our roofs are removed. This is what I call badly-done.

That's why when I saw your mod I was thinking that this workaround to place lanterns on slabs was genius ! The block under the lantern doesn't change at all, if we remove your mod, only the lantern (which is decorative not essential) is removed. So what if we used this workaround to be able to put snow on stairs/slabs/fences/walls ?

Because of the Covid-19 I had many time to create all models you need for this workaround. All snow variants possible is under the normal block so it fits what's under. 

For the fence and the wall, it would have a ground and an air variant : on the ground it would have normal snow layers on the ground + on the fence itself, and the air variant would only have the snow on the fence and not the layers on the ground.

Here is the Zip containing every snow variant 👍 
[snow-on-everything.zip](https://github.com/EndlesNights/TorchSlab/files/4361899/snow-on-everything.zip)

**Comment by EndlesNights** [comment]
You know it's funny that you mention that because here is something else I've been working on. If you want to chat more message more over discord @EndlesNights#9000
![2020-02-22_01 30 57](https://user-images.githubusercontent.com/58280840/77210002-3dc3a900-6ad6-11ea-8402-1cfdafc0f881.png)
![2020-02-27_18 30 57](https://user-images.githubusercontent.com/58280840/77210029-4e741f00-6ad6-11ea-94a7-bd8a5a864835.png)

**Comment by Matthysse** [comment]
Ok I asked you on discord. My idea is to separate the mod which allows new slab and generation of them with the mod which allows to put snow on everything.

**Comment by EndlesNights** [comment]
It's a fun idea. Though it's outside of the scope of torches, and torch like elements (lanterns & candles) so it won't be part of this mod. Closing this issue, if you have any further comments we can discus them over Discord.
