### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by EternalOne11** [EndlesNights/TorchSlab#8]
I recived this crash report when using buzzier bees 1.4 test build. They siad this was an issue on your end. https://paste.dimdev.org/mucopojube.md

**Comment by EndlesNights** [comment]
Current compatability support is only set for version Bee1.3. I'll see what changes they made and update to support 1.4 tomorrow.

**Comment by EndlesNights** [comment]
Basic support for buzzier bees 1.4 has been implemented. Full support for the candles made from other mods will be added at a later time.
