### ISSUE TITLE
Another day, another crash

### ISSUE THREAD

**Issue by SissyTrashQueen** [EndlesNights/TorchSlab#9]
MC Version: 1.15.2
Forge version: 31.1.30
Torch Slabs Mod: v1.6.3
[latest.log](https://paste.gg/p/anonymous/5c35fcc4a7b84a2e96b8e085339e14b7)
[debug.log part](https://paste.gg/p/anonymous/849e5bd41011431b90548310f48a4e99)

One of the things I did today was update the Carpet Stairs Mod. But I don't think that's the cause

~~I know I'm kind of wishing to crash with so many mods~~

**Comment by SissyTrashQueen** [comment]
It seems it isn't this mod's fault lol (This is what happens when you're late at night and want to go to bed without trying anything) I can't close this

**Comment by EndlesNights** [comment]
I've been there before. Enjoy your self.
